### ISSUE TITLE
Unable to take pictures Android N (Nexus 6P) (Targeting API 24)

### ISSUE THREAD

**Issue by ilber** [jamesmontemagno/MediaPlugin#106]
Unable to take pictures on Android 7. Probably this is due to changes on android/permissions

## Bug 

Version Number of Plugin: 2.3.0 (Latest Master Cloned Project)
Device Tested On: Nexus 6 P
Simulator Tested On: No

LOG:

<addr>
XXXXX:Error:2016-10-13 10:51:20.977: Exception:[FileUriExposedException] file:///storage/emulated/0/Android/data/XXXXX.XXXXX.XXXXX_ng/files/Pictures/IMG_20161013_125120.jpg exposed beyond app through ClipData.Item.getUri();   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000a7] in /Users/builder/data/lanes/3819/96c7ba6c/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12083 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00068] in /Users/builder/data/lanes/3819/96c7ba6c/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:31 
  at Android.App.Activity.StartActivityForResult (Android.Content.Intent intent, System.Int32 requestCode) [0x0003f] in /Users/builder/data/lanes/3819/96c7ba6c/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.App.Activity.cs:5908 
  at Plugin.Media.MediaPickerActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00202] in /Users/XXXXX/Projects/MediaPlugin/src/Media.Plugin.Android/MediaPickerActivity.cs:156 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357 
  at Plugin.Media.MediaImplementation+<TakePhotoAsync>c__async1.MoveNext () [0x0010e] in /Users/XXXXX/Projects/MediaPlugin/src/Media.Plugin.Android/MediaImplementation.cs:166 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357 
  at XXXXX.Core.Conversations.ViewModels.XXXXXChatViewModel+<DoTakePhotoAsync>c__async3.MoveNext () [0x00218] in /Users/XXXXX/XXXXX/app/Core/XXXXX.Core/Conversations/ViewModels/XXXXXChatViewModel.cs:436 
  --- End of managed Android.OS.FileUriExposedException stack trace ---
android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/XXXXX.XXXXX.XXXXX_ng/files/Pictures/IMG_20161013_125120.jpg exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
	at android.net.Uri.checkFileUriExposed(Uri.java:2346)
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:8909)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
	at android.app.Activity.startActivityForResult(Activity.java:4224)
	at android.app.Activity.startActivityForResult(Activity.java:4183)
	at md588a879adf152f547778e5147cb2024ef.MediaPickerActivity.n_onCreate(Native Method)
	at md588a879adf152f547778e5147cb2024ef.MediaPickerActivity.onCreate(MediaPickerActivity.java:41)
	at android.app.Activity.performCreate(Activity.java:6664)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
</addr>

**Comment by jamesmontemagno** [comment]
I would install the latest beta to see if that fixes it for you. I have a 6P with no issues both on this version and with the other. 2.3.0 handles permissions on Android just fine.

**Comment by jamesmontemagno** [comment]
I am on 7.0, the issue you are looking at is something with strict mode: http://stackoverflow.com/questions/32623304/when-take-photo-get-java-lang-throwable-file-uri-exposed-through-clipdata test out the 2.6.0 beta and let me know your findings.

**Comment by jamesmontemagno** [comment]
Additionally, what camera app are you using?

**Comment by ilber** [comment]
Hi James,
Thank you very much for your quick reply.
We are using the default google camera app to take pictures.
Any settings that we have to change somewhere?

**Comment by jamesmontemagno** [comment]
Not that I know of it is working flawless on my Nexus 6P with 7.0 installed so not sure.

I can't really solve device specific issues perhaps some IT setting. Going to close as I can not repo.

**Comment by jamesmontemagno** [comment]
Going to re-open... are you targeting Android N (API 24) or API 23?

**Comment by ilber** [comment]
Yes James we are targeting Android API 24.

**Comment by jamesmontemagno** [comment]
Gotcha, Yeah I was targeting 23 that is why. So 2.3/2.6 currently you will need to target API 23 until I can configure some changes in Android N.

**Comment by ilber** [comment]
Perfect. If u need some help just let m know.

**Comment by jamesmontemagno** [comment]
You will now need to update to 2.6.0.9-beta if you want to Target Android N.

Then you will need to do the following:

ANDROID N If your application targets Android N (API 24) or newer, you must use version 2.6.0+.

You must also add a few additional configuration files to adhere to the new strict mode:

1.) Add the following to your AndroidManifest.xml inside the <application> tags:
```
<provider android:name="android.support.v4.content.FileProvider" 
                android:authorities="YOUR_APP_PACKAGE_NAME.fileprovider" 
                android:exported="false" 
                android:grantUriPermissions="true">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" 
                android:resource="@xml/file_paths"></meta-data>
</provider>
```
YOUR_APP_PACKAGE_NAME must be set to your app package name!

2.) Add a new folder called xml into your Resources folder and add a new XML file called file_paths.xml

Add the following code:
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="my_images" path="Android/data/YOUR_APP_PACKAGE_NAME/files/Pictures" />
    <external-path name="my_movies" path="Android/data/YOUR_APP_PACKAGE_NAME/files/Movies" />
</paths>
```
YOUR_APP_PACKAGE_NAME must be set to your app package name!

You can read more at: https://developer.android.com/training/camera/photobasics.html
