### ISSUE TITLE
Open Camera Crash

### ISSUE THREAD

**Issue by Vandersteen** [jamesmontemagno/MediaPlugin#142]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.6.1
Device Tested On: Motorola G3
Simulator Tested On:

### Expected Behavior
Open the camera
### Actual Behavior
Crashes

### Steps to reproduce the Behavior

Java.Interop.JniEnvironmentAttempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
Raw
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3b84f27a27ec4ea69da2efa160a8d4e4>:0 
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00082] in <12768712d46d44ddb9bb0a23a3ff8701>:0 
  at Android.Runtime.JNIEnv.CallStaticObjectMethod (System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <aaab93ff40364651ae8e3a9847ecc6df>:0 
  at Android.Support.V4.Content.FileProvider.GetUriForFile (Android.Content.Context context, System.String authority, Java.IO.File file) [0x00078] in <27c17fe440cf491ba8255bcefade6e02>:0 
  at Plugin.Media.MediaPickerActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00237] in <5e1063f9398646e4b3057633697ce258>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3b84f27a27ec4ea69da2efa160a8d4e4>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <3b84f27a27ec4ea69da2efa160a8d4e4>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <3b84f27a27ec4ea69da2efa160a8d4e4>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <3b84f27a27ec4ea69da2efa160a8d4e4>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <3b84f27a27ec4ea69da2efa160a8d4e4>:0 
  at Plugin.Media.MediaImplementation+<TakePhotoAsync>d__18.MoveNext () [0x0011a] in <5e1063f9398646e4b3057633697ce258>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3b84f27a27ec4ea69da2efa160a8d4e4>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <3b84f27a27ec4ea69da2efa160a8d4e4>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <3b84f27a27ec4ea69da2efa160a8d4e4>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <3b84f27a27ec4ea69da2efa160a8d4e4>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <3b84f27a27ec4ea69da2efa160a8d4e4>:0 
  at B2B.AskPicturePage+<OpenCameraButton_Clicked>c__async0.MoveNext () [0x00464] in <9a54bfd161ef4b28988249cc2083067c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3b84f27a27ec4ea69da2efa160a8d4e4>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in <3b84f27a27ec4ea69da2efa160a8d4e4>:0 
  at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in <aaab93ff40364651ae8e3a9847ecc6df>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in <aaab93ff40364651ae8e3a9847ecc6df>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <aaab93ff40364651ae8e3a9847ecc6df>:0 
  at (wrapper dynamic-method) System.Object:849df66f-3e62-4a4b-9dd7-6b352c00ae7a (intptr,intptr)
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
	at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:560)
	at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:534)
	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:376)
	at md5447fdd08b040856919d3dd3a41d94bac.MediaPickerActivity.n_onCreate(Native Method)
	at md5447fdd08b040856919d3dd3a41d94bac.MediaPickerActivity.onCreate(MediaPickerActivity.java:41)
	at android.app.Activity.performCreate(Activity.java:6259)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by jamesmontemagno** [comment]
Please provide a sample that you are trying. I assume you did not follow the direction in the readme or the github for Android's file provider. Read through that.

Please don't post a stack trace here, post it on http://gist.github.com.

Follow these and then re-post a new if you still have issues.

**Comment by Dan27F** [comment]
I have the same problem, in device moto g3.
