### ISSUE TITLE
Android: ClassNotFoundException for MediaPickerActivity

### ISSUE THREAD

**Issue by timbrand** [jamesmontemagno/MediaPlugin#176]
## Bug 

The latest beta-version (2.6.3.6-beta) is resulting in an exception. I've tried al other 2.6.3 beta's but they all run fine.

Stacktrace:
`[monodroid] JNIEnv.FindClass(Type) caught unexpected exception: Java.Lang.ClassNotFoundException: md50c633ad00ae623098997db16276ce64c.MediaPickerActivity ---> Java.Lang.NoClassDefFoundError: md50c633ad00ae623098997db16276ce64c/MediaPickerActivity ---> Java.Lang.ClassNotFoundException: Didn't find class "md50c633ad00ae623098997db16276ce64c.MediaPickerActivity" on path: /data/app/com.********.apk
[monodroid]    --- End of inner exception stack trace ---
[monodroid]    --- End of inner exception stack trace ---
[monodroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/88113ba4/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
[monodroid]   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00082] in /Users/builder/data/lanes/4009/88113ba4/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12649 
[monodroid]   at Android.Runtime.JNIEnv.CallStaticObjectMethod (System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x00000] in /Users/builder/data/lanes/4009/88113ba4/source/monodroid/src/Mono.Android/JNIEnv.g.cs:562 
[monodroid]   at Android.Runtime.JNIEnv.CallStaticObjectMethod (System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue[] parms) [0x0001d] in /Users/builder/data/lanes/4009/88113ba4/source/monodroid/src/Mono.Android/JNIEnv.g.cs:568 
[monodroid]   at Android.Runtime.JNIEnv.FindClass (System.String classname) [0x00007] in /Users/builder/data/lanes/4009/88113ba4/source/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:602 
[monodroid]   at Android.Runtime.JNIEnv.FindClass (System.Type type) [0x00009] in /Users/builder/data/lanes/4009/88113ba4/source/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:542 
[monodroid]   --- End of managed Java.Lang.ClassNotFoundException stack trace ---
[monodroid] java.lang.ClassNotFoundException: md50c633ad00ae623098997db16276ce64c.MediaPickerActivity
[monodroid] 	at java.lang.Class.classForName(Native Method)
[monodroid] 	at java.lang.Class.forName(Class.java:204)
[monodroid] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.GenericMenuClickListener.n_onMenuItemClick(Native Method)
[monodroid] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.GenericMenuClickListener.onMenuItemClick(GenericMenuClickListener.java:30)
[monodroid] 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
[monodroid] 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
[monodroid] 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
[monodroid] 	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
[monodroid] 	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
[monodroid] 	at android.view.View.performClick(View.java:4475)
[monodroid] 	at android.view.View$PerformClick.run(View.java:18786)
[monodroid] 	at android.os.Handler.handleCallback(Handler.java:730)
[monodroid] 	at android.os.Handler.dispatchMessage(Handler.java:92)
[monodroid] 	at android.os.Looper.loop(Looper.java:176)
[monodroid] 	at android.app.ActivityThread.main(ActivityThread.java:5419)
[monodroid] 	at java.lang.reflect.Method.invokeNative(Native Method)
[monodroid] 	at java.lang.reflect.Method.invoke(Method.java:525)
[monodroid] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
[monodroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
[monodroid] 	at dalvik.system.NativeStart.main(Native Method)
[monodroid] Caused by: java.lang.NoClassDefFoundError: md50c633ad00ae623098997db16276ce64c/MediaPickerActivity
[monodroid] 	... 20 more
[monodroid] Caused by: java.lang.ClassNotFoundException: Didn't find class "md50c633ad00ae623098997db16276ce64c.MediaPickerActivity" on path: /data/app/com.*******.apk
[monodroid] 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:64)
[monodroid] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
[monodroid] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
[monodroid] 	... 20 more
`

Version Number of Plugin: 2.6.3.6-beta
Device Tested On: Android  (Galaxy s3 and OnePlus One)
Simulator Tested On:

### Expected Behavior
Pick or Take  photo should show the image-picker;

### Actual Behavior
Pick or take a photo results in an CalssNotFound Exception.

### Steps to reproduce the Behavior
await Plugin.Media.CrossMedia.Current.Initialize();
await CrossMedia.Current.PickPhotoAsync();

I've not changed anything in my own code. When going back to an older beta-version, it works fine again.

**Comment by timbrand** [comment]
I was still figuring out what the error could be, and I noticed that on the other beta-builds I also had an exception. After some switching between version, I now also have that same exception on the latest build too. It happens after selected an image:

`  at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[TAntecedentResult,TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/4009/88113ba4/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:207 
  at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/4009/88113ba4/source/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/88113ba4/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/4009/88113ba4/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/4009/88113ba4/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/4009/88113ba4/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/4009/88113ba4/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357 
  at Plugin.Media.MediaPickerActivity+<OnActivityResult>d__30.MoveNext () [0x0016e] in C:\projects\mediaplugin\src\Media.Plugin.Android\MediaPickerActivity.cs:345 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/88113ba4/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in /Users/builder/data/lanes/4009/88113ba4/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018 
  at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/4009/88113ba4/source/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:35 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/4009/88113ba4/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/4009/88113ba4/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Java.Lang.IRunnable.cs:81 
  at (wrapper dynamic-method) System.Object:143e41bf-d431-4939-83c0-b7bdf29dcf41 (intptr,intptr)`

**Comment by timbrand** [comment]
I'm not sure, but it looks like the latest nuget package is maybe somehow incorrect.
When using the beta-package it it drops me with an exception that the constructor method of is missing. So I tried the following in my app:

`var media = new Plugin.Media.Abstractions.MediaFile("", () => { return null; }, "");`

This resulted in the same exception.

Now I downloaded a copy of the source and added the projects as reference manually (and of course removed the nuget). With this change it's working fine. 
So it seems that the code is working fine, only the nuget-package seems to be "corrupt" ?

**Comment by jamesmontemagno** [comment]
What Linker settings are you using? It may be stripping out information.

**Comment by timbrand** [comment]
I've only tested it on Debug configuration yet, and my linker configuration in debug is on "Don't Link".

**Comment by jamesmontemagno** [comment]
Have you tried the current stable? to verify at all.

**Comment by jamesmontemagno** [comment]
Can you try the latest latest beta.

**Comment by timbrand** [comment]
Tested the latest beta (v2.6.3.8) and this seems to have fixed the issue!
Thanks!

**Comment by JohnHunterPartholan** [comment]
Hi, I'm receiving exactly the same error with any version over 2.6.2 when running on any version of KitKat, v2.6.3+ works fine on Lollipop and above.

`/monodroid( 2986): JNIEnv.FindClass(Type) caught unexpected exception: Java.Lang.ClassNotFoundException: md5a3e164e78ade0c22cefea770ddd0bc49.MediaPickerActivity ---> Java.Lang.NoClassDefFoundError: md5a3e164e78ade0c22cefea770ddd0bc49/MediaPickerActivity ---> Java.Lang.ClassNotFoundException: Didn't find class "md5a3e164e78ade0c22cefea770ddd0bc49.MediaPickerActivity" on path: DexPathList[[zip file "/data/app/com.test.app-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.test.app-1, /vendor/lib, /system/lib]]
W/monodroid( 2986):    --- End of inner exception stack trace ---
W/monodroid( 2986):    --- End of inner exception stack trace ---
W`
