### ISSUE TITLE
CameraCaptureUI is Not Registered

### ISSUE THREAD

**Issue by jotprabh1** [jamesmontemagno/MediaPlugin#212]
## Bug 

Version Number of Plugin: 2.6.2
Device Tested On: Laptop running Windows 8.1
Simulator Tested On: -

### Expected Behavior
Take Picture

### Actual Behavior
Exception - CameraCaptureUI Class not registered

### Steps to reproduce the Behavior
            await CrossMedia.Current.Initialize();
            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                    await DisplayAlert("Error", "No Camera Available", "OK");
            var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    Directory = "ABC",
                    Name = filename,
                    PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium
                });

StackTrace:
Requested Windows Runtime type 'Windows.Media.Capture.CameraCaptureUI' is not registered.
at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Windows.Media.Capture.CameraCaptureUI..ctor()
   at Plugin.Media.MediaImplementation.<TakePhotoAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Timble.Details.<takePicture>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Timble.Details.<BtnMarkAtt_Clicked>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

**Comment by jotprabh1** [comment]
Solution:
Found the solution to this problem. The problem was that Windows Media Feature Pack was not installed. So, installed it from Microsoft website. Now, the camera is working perfectly fine.
