### ISSUE TITLE
XAMLParseException in CrossMedia.Current.TakePhotoAsync - WindowsPhone

### ISSUE THREAD

**Issue by kirrek** [jamesmontemagno/MediaPlugin#33]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.3.0
Device Tested On: Emulator Windows Phone
Simulator Tested On: Emulator 8.1 WVGA 4 inch 512MB

### Expected Behavior

Show Camera

### Actual Behavior

Crash with XAML parseException when executing:

### Steps to reproduce the Behavior

When executing the following code crash with XAMLParseException:

var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
            {
                Directory = "AAAAA",
                Name = string.Format("aaaa_{0}.jpg", DateTime.Now.ToString("yyyyMMddhhmmss", CultureInfo.InvariantCulture))
            });

## Feature Request:
How to fix it

Thank you very much

**Comment by ahmedalejo** [comment]
It´d be great to see the `XAMLParseException.Message`

**Comment by kirrek** [comment]
The exception is the following:

$exception  {"XAML parsing failed."}    Windows.UI.Xaml.Markup.XamlParseException
Exception thrown: 'Windows.UI.Xaml.Markup.XamlParseException' in mscorlib.ni.dll

at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at DMX.Helper.CameraCaptureUI.InitializeComponent()
   at DMX.Helper.CameraCaptureUI..ctor()
   at Media.Plugin.MediaImplementation.<TakePhotoAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AppName.Data.Views.Page.<PhotoClick>d__2.MoveNext()

Thanks,

**Comment by jamesmontemagno** [comment]
Please test out: 2.5.0-beta5

**Comment by jamesmontemagno** [comment]
Fixed officially in 2.5.1-beta33! Tested and shipped!
