### ISSUE TITLE
Attempt to invoke virtual method ... on a null object reference

### ISSUE THREAD

**Issue by Manu404** [jamesmontemagno/MediaPlugin#347]
Really urgent, we have the crash in production to our clients, we do not know exactly how that start, but it seems related to our last release. No changes have been made on our last release on the camera sub system. Thank you in advance for you help, we're in a bad situation, camera is core in our app.

## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: Sony Experia D2303
Simulator Tested On: None
Version of VS: 2017 15.2 26430.13 Release
Version of Xamarin: 2.3.4.270
Versions of other things you are using:

### Steps to reproduce the Behavior

Simply open the camera picker

### Expected Behavior

The camera picker opens

### Actual Behavior

I get an exception on TakePhotoAsync:

Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(androir.content.pm.PackageManager, java.lang.String)' on a null object reference

### Code snippet

My TakePhoto method:

        private async Task<MediaFile> TakePhoto(string fileName, string extension)
        {
            await CrossMedia.Current.Initialize();

            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                await MessagePopup.Show("Pas d'appareil photo de disponnible.");
                return null;
            }

            var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
            {
                Name = $"{fileName}_full.{extension}",
                AllowCropping = false,
                PhotoSize = PhotoSize.Medium,
                CompressionQuality = 100,
                SaveToAlbum = true
            });

            return file;
        }

My Android manifest:

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:installLocation="auto" android:versionCode="1001600" package="eu.igsoft.carpack.mobile" android:versionName="1.0.16 - Silver Marble">
	<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="25" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.CAMERA" />
	<application android:icon="@drawable/icon" android:label="CarPack Mobile"></application>
</manifest>

**Comment by Manu404** [comment]
I found the solution, I switched the Target Android Version to 7.1 API 25 instead of 6.0 API 23.

I switched back the solution to API 23, now it's working again.

Look like you have trouble with the latest API version or is it something on my side ?

Best

**Comment by prashantvc** [comment]
@Manu404 is this specific to Sony Experia devices? Do you see this issue on other devices too? It will really help if you could share _full exception stacktrace_ and _adb log_

**Comment by Manu404** [comment]
@prashantvc I will get you the full stacktrace and adb log ASAP.

We had the error on every android devices, I have some samsung devices, they all crash with the same exception.

**Comment by Manu404** [comment]
@prashantvc So, I changed the Target Android Version to SDK 25 and changed the target framework to use the SDK 25 compiler.

Here's the stacktrace I have:

`Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference`

  ```
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <bd30a18775d94dc8b6263aecd1ca9077>:0 
  at Android.Runtime.JNIEnv.CallStaticObjectMethod (System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <d855bac285f44dda8a0d8510b679b1e2>:0 
  at Android.Support.V4.Content.FileProvider.GetUriForFile (Android.Content.Context context, System.String authority, Java.IO.File file) [0x00078] in <3e239b9681084d42bb949c1e01ef500e>:0 
  at Plugin.Media.MediaPickerActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0023f] in C:\projects\mediaplugin\src\Media.Plugin.Android\MediaPickerActivity.cs:162 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at Plugin.Media.MediaImplementation+<TakePhotoAsync>d__16.MoveNext () [0x000c7] in C:\projects\mediaplugin\src\Media.Plugin.Android\MediaImplementation.cs:119 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at IGSoft.CarPack.Mobile.Core.Helper.CameraHelper+<TakePhoto>d__2.MoveNext () [0x00186] in D:\IGSoft\CarPackMobile 2\trunk\Client\IGSoft.CarPack.Mobile\Core\Helper\CameraHelper.cs:38 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at IGSoft.CarPack.Mobile.Core.Helper.CameraHelper+<TakePhoto>d__3.MoveNext () [0x000d8] in D:\IGSoft\CarPackMobile 2\trunk\Client\IGSoft.CarPack.Mobile\Core\Helper\CameraHelper.cs:61 
  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
	at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
	at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
	at md5f1b52d9f1d5d1981437e7e130649468a.MediaPickerActivity.n_onCreate(Native Method)
	at md5f1b52d9f1d5d1981437e7e130649468a.MediaPickerActivity.onCreate(MediaPickerActivity.java:42)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
	at android.app.ActivityThread.access$800(ActivityThread.java:156)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5371)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:945)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:740)

```
I looked at the logcat of the Android Device Monitor but I can't find any error in there when I try to take a photo

**Comment by jamesmontemagno** [comment]
This is because you didn't add your paths.xml correctly: https://github.com/jamesmontemagno/mediaplugin#android-n

**Comment by Manu404** [comment]
@jamesmontemagno Thanks ! I missed that as the first implementation was targetting API 23 so no need for it. I will implement that change.
