### ISSUE TITLE
The app runs well with Media Plugin in Emulator but fails in real device.

### ISSUE THREAD

**Issue by vibhav45** [jamesmontemagno/MediaPlugin#470]
Version Number of Plugin: 3.1.3
Device Tested On: Redmi 4A
Simulator Tested On: Android
Version of VS: 2017
Version of Xamarin: 4.8.0
Versions of other things you are using:

The code runs fine on Visual Studio Emulators but crashes on physical device giving the following error.

android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.InternalSetPage (Xamarin.Forms.Page page) [0x0006f] in <aa25dff89f734b22b9ab88fd01c78705>:0 
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.SetMainPage () [0x0000c] in <aa25dff89f734b22b9ab88fd01c78705>:0 
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.LoadApplication (Xamarin.Forms.Application application) [0x0025c] in <aa25dff89f734b22b9ab88fd01c78705>:0 
  at InterestMatch.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00033] in <9e2a066af7c24de6828dc3a0f4e22d31>:0 
  at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <1e89c43d3c7d48b5ba69bfc0b1bdf114>:0 
  at (wrapper dynamic-method) System.Object:6b534aff-3541-46f2-a92e-ac0022b9c4a7 (intptr,intptr,intptr)
	at md5ed93386354f0e17f050b2885712023ca.MainActivity.n_onCreate(Native Method)
	at md5ed93386354f0e17f050b2885712023ca.MainActivity.onCreate(MainActivity.java:29)
	at android.app.Activity.performCreate(Activity.java:6303)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
	at android.app.ActivityThread.access$1000(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:5523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by jamesmontemagno** [comment]
Maybe you are linking something out. Not sure, works for me just fine. Can't help without a repo.
