### ISSUE TITLE
Getting error on PickPhotoAsync() 

### ISSUE THREAD

**Issue by ashishbpatil1** [jamesmontemagno/MediaPlugin#503]
I am getting following error on Lenovo K8 Note Android 7.1.1 on line 
`var file = await CrossMedia.Current.PickPhotoAsync();`
 It is working on other devices like Samsung Galaxcy S6 edge+ (Android v7.0), Samsung J7 Pro (Android v7.0), Asus Zen Phone 3 (Android v8.0), Pixel 2 (Android v8.1.0).

## Bug Information

Version Number of Plugin: 3.1.3
Device Tested On: Lenovo K8 Note (Android 7.1.1)
Version of VS: 2017 Professional latest
Version of Xamarin Forms: 2.5.0.280555
Versions of Plugin.CurrentActivity: 1.0.1 

### Steps to reproduce the Behavior
1. Implemented all steps given in MediaPlugin Document.
2. Set following in android properties:
```
Compile using Android version : (Target Framework) 
Android 8.0 (Oreo)
Minimum Android Version: 
Android 4.0.3 ( API Level 15 - Ice Cream Sandwich)
Target Android version: 
Android 8.0 ( API Level 26- Oreo)

```
3. Run the project on Lenovo K8 Note Android Version 7.1.1. 

### Expected Behavior
It should able to pick picture from Gallary. It is working on other devices like Galaxcy S6 edge+ (Android v7.0), Samsung J7 Pro (Android v7.0), Asus Zen Phone 3 (Android v8.0), Pixel 2 (Android v8.1.0).

### Actual Behavior
Throws following error.
### Exception Logged

```
{Android.Content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK typ=image/* }
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, 
Java.Interop.JniArgumentValue* args) [0x00089] in <3cb12bce834a498199b2be6cd3e00922>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, 
Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <3cb12bce834a498199b2be6cd3e00922>:0  
at Android.App.Activity.StartActivityForResult (Android.Content.Intent intent, System.Int32 requestCode) [0x00044] in <0f4fdd9de5d4461ca741cbb9871ad0ce>:0  
at Plugin.Media.MediaPickerActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00280] in C:\projects\mediaplugin\src\Media.Plugin.Android\MediaPickerActivity.cs:181 
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
  at Plugin.Media.MediaImplementation+<PickPhotoAsync>d__16.MoveNext () [0x000aa] in C:\projects\mediaplugin\src\Media.Plugin.Android\MediaImplementation.cs:91 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fcbf47a04b2e4d90beafbae627e1fca4>:0  
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <fcbf47a04b2e4d90beafbae627e1fca4>:0  
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <fcbf47a04b2e4d90beafbae627e1fca4>:0  
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <fcbf47a04b2e4d90beafbae627e1fca4>:0  
at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <fcbf47a04b2e4d90beafbae627e1fca4>:0  
at Jvp.PaymentPage+<pickPictureButton_Clicked>d__17.MoveNext () [0x00117] in D:\Jvp\Jvp\Jvp\Jvp\Views\PaymentPage.xaml.cs:617  
--- End of managed Android.Content.ActivityNotFoundException stack trace 
---
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK typ=image/* }	
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1899)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1589)	
at android.app.Activity.startActivityForResult(Activity.java:4257)
at android.app.Activity.startActivityForResult(Activity.java:4201)	
at md5dff1bed22da39876f271fd39214b8f60.MediaPickerActivity.n_onCreate(Native Method)
at md5dff1bed22da39876f271fd39214b8f60.MediaPickerActivity.onCreate(MediaPickerActivity.java:42)	
at android.app.Activity.performCreate(Activity.java:6715)	
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)	
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2711)	
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2827)	
at android.app.ActivityThread.-wrap12(ActivityThread.java)	
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1559)	
at android.os.Handler.dispatchMessage(Handler.java:110)	
at android.os.Looper.loop(Looper.java:203)	
at android.app.ActivityThread.main(ActivityThread.java:6369)	
at java.lang.reflect.Method.invoke(Native Method)	
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1090)	
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:951)
}

```

### Code snippet
```
 private async void PickPicture_Clicked(object sender, EventArgs e)
 {
     try
     {
	if (!CrossMedia.Current.IsPickPhotoSupported)
        {
            await DisplayAlert("Error", "Can not access the Gallery!", "OK");
            return;
         }
         var file = await CrossMedia.Current.PickPhotoAsync();
         if (file == null)
             return;
                
          imagepath = file.Path;
          ImageS.Source = ImageSource.FromStream(() => file.GetStream());
      }
      catch (Exception ex)
      {
                
      }
}

```

Please help to resolve this issue.
Thanks in advance.

**Comment by ashishbpatil1** [comment]
After enabling Google Photos it worked.
Please close this issue.
But there must be photo viewer available on mobile device.
And if Google Photos is disabled on mobile the 
`CrossMedia.Current.IsPickPhotoSupported`
returns true which should not.

Thanks for the plugin.
