### ISSUE TITLE
ActivityNotFoundException when running sample on device with Android 8.1(API 27)

### ISSUE THREAD

**Issue by bbl-Laobu** [jamesmontemagno/MediaPlugin#638]
The sample app does not run on a device with Andoid 8.1. It crashes with error "ActivityNotFoundException" when pressing the "Take Photo" button. 
Running the app on a device with API23 works fine. 

## Bug Information

Version Number of Plugin: 4.0.1.5
Device Tested On: Android 8.1(API 27). HMD Global Nokia Model TA-1047
Simulator Tested On:
Version of VS: 7.7 (Mac) and v15.9.3 (pc)
Version of Xamarin: 3.1.0.637273 
Versions of other things you are using:

### Steps to reproduce the Behavior
Run the sample on a real device with android 8.1. Then tap "Take photo" button  -> App Crashes with ActivityNotFoundException

Please note that this was also tested on a (API 23) Huawai BG2-W09 device where there was no problem. 

### Expected Behavior
Camera viewer should open

### Actual Behavior
The App Crashes with the following error:

{Android.Content.ActivityNotFoundException: No Activity found to handle Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 clip={text/uri-list U:content://com.plugin.mediatest.fileprovider/my_images/Test/IMG_20181205_141408.jpg} (has extras) }
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <0ad2222fd7074badb5de547b1521aab0>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <0ad2222fd7074badb5de547b1521aab0>:0 
  at Android.App.Activity.StartActivityForResult (Android.Content.Intent intent, System.Int32 requestCode) [0x00044] in <ad2f15102b3a4d36b40e9b0cbc11c376>:0 
  at Plugin.Media.MediaPickerActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00307] in <5939e997f291496f805023da28f3a447>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Plugin.Media.MediaImplementation+<TakePhotoAsync>d__17.MoveNext () [0x00112] in <5939e997f291496f805023da28f3a447>:0 
--- End of stack trace from previous location where exception was thrown ---
  at MediaSample.MediaPage+<<-ctor>b__0_0>d.MoveNext () [0x000cf] in /Users/mac/GITVS/jamesmontemagno/MediaPlugin.git/samples/MediaSample/MediaSample/MediaPage.xaml.cs:29 
  --- End of managed Android.Content.ActivityNotFoundException stack trace ---
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 clip={text/uri-list U:content://com.plugin.mediatest.fileprovider/my_images/Test/IMG_20181205_141408.jpg} (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1937)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
	at android.app.Activity.startActivityForResult(Activity.java:4501)
	at android.app.Activity.startActivityForResult(Activity.java:4459)
	at md54cd65ac53ae710bff80022afc423e0f3.MediaPickerActivity.n_onCreate(Native Method)
	at md54cd65ac53ae710bff80022afc423e0f3.MediaPickerActivity.onCreate(MediaPickerActivity.java:42)
	at android.app.Activity.performCreate(Activity.java:7023)
	at android.app.Activity.performCreate(Activity.java:7014)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2758)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2883)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
}

### Code snippet
Note: I did add a tryy catch around the TakePhotoAsync call to capture the error

> MediaFile file = null;
				try
				{
					file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
					{
						Directory = "Test",
						SaveToAlbum = true,
						CompressionQuality = 75,
						CustomPhotoSize = 50,
						PhotoSize = PhotoSize.MaxWidthHeight,
						MaxWidthHeight = 2000,
						DefaultCamera = CameraDevice.Front
					});
				}
				catch (Exception ex)
				{
					DisplayAlert("No Camera", ":( No camera available." + ex.Message, "OK");
				}

**Comment by bbl-Laobu** [comment]
Hey James, 
It's been a while as I have been busy with some other things.
In the meantime, I still seem to have the same issue even after clean/rebuild.
For the linker options, I am not sure in what way I should change the settings.

I also downloaded and ran the sample project which gives me the same problem:
----
Unhandled Exception:

Android.Content.ActivityNotFoundException: No Activity found to handle Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 clip={text/uri-list U:content://com.plugin.mediatest.fileprovider/my_images/Test/IMG_20190515_163735.jpg} (has extras) }
----

Again, this works fine on other Android devices but seems a problem on the Nokia (android 8.1 - API 27)

Lastly, I also tried with version v4.2.0-beta, but with no luck.

Any further suggestions?
Bernard

**Comment by bbl-Laobu** [comment]
So, I've been digging into the Media plugin and it seems that the StartActivityForResult call is the culprit (MediaPickerActivity.cs:218 ). I guess the Intent created is not valid for this particular device.
I would like to test it by creating a new pickIntent just before the call. Any suggestions what I can hard-code to test and so I can see what works for this device? I guess once we know that we should be able to adapt the code creating the pickIntent to adapt to the particulars of this Nokia device... Or any other suggestions?

  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <286213b9e14c442ba8d8d94cc9dbec8e>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <286213b9e14c442ba8d8d94cc9dbec8e>:0 
  at Android.App.Activity.StartActivityForResult (Android.Content.Intent intent, System.Int32 requestCode) [0x00044] in <95d915721ad748108ff096dce8f8f32c>:0 
  at Plugin.Media.MediaPickerActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x003d5] in C:\Git\MediaPlugin\src\Media.Plugin\Android\MediaPickerActivity.cs:218 
  --- End of managed Android.Content.ActivityNotFoundException stack trace ---
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 clip={text/uri-list U:content://com.companyname.Media.Plugin.Sample.fileprovider/my_images/Sample/test_2.jpg} (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1937)
	...

**Comment by jamesmontemagno** [comment]
Could be that device and camera don't support another app launching it to take a photo. download another camera app maybe?

**Comment by bbl-Laobu** [comment]
Well keeping that in mind, I've been testing another few plugins to see if they get the camera to work.
The CameraAppDemo2 for Xamarin.Android seems to at least start the viewer. Unfortunately, it can not safe the picture for some reason to the device. 
The old ZXing barcode scanning plugin works perfectly. No image saving for this plugin.

So, could the saving of the image have anything to do with it? Any ideas are welcome...

In the meantime, would you mind reopening this issue? Just in case someone else had this problem and found a solution. Thanks!

**Comment by zjmsky** [comment]
hi,i have the same problem,do you solved this?

**Comment by bbl-Laobu** [comment]
Unfortunately, I didn’t find the time to further investigate this. Tbh, I was also hoping that by now the new XF Cameraview would be ready. It seems planned for Sep/Oct for now but not sure if the team will be able to respect this timetable. 
So, I wouldn’t mind that this problem here would get solved as not having a 100% functional camera plugin for XF is not ideal.
Let me know if you find a solution please.

**Comment by BeranekCZ** [comment]
I have this erro on Android 5.1.1.  Anything new?
