### ISSUE TITLE
Selected image crash on Xamarin Anroid

### ISSUE THREAD

**Issue by Firice** [jamesmontemagno/MediaPlugin#709]
Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information
I using on Xamarin IOS everything is ok but xamarin android when i selected image then crash app

Version Number of Plugin: 4.0.1.5
Device Tested On: 
Simulator Tested On: Genymotion Samsung Galaxy S9
Version of VS: 8.1 (Build 2742)
Version of Xamarin: 4.0.0.482894
Versions of other things you are using:

### Actual Behavior
`[ExifInterface] Encountered exception while getting thumbnail
[ExifInterface] java.io.IOException: Corrupted image
[ExifInterface] 	at android.media.ExifInterface.getThumbnailBytes(ExifInterface.java:1888)
[ExifInterface] 	at android.media.ExifInterface.getThumbnail(ExifInterface.java:1844)
[ExifInterface] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[ExifInterface] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
[ExifInterface] 	at android.os.Handler.handleCallback(Handler.java:789)
[ExifInterface] 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ExifInterface] 	at android.os.Looper.loop(Looper.java:164)
[ExifInterface] 	at android.app.ActivityThread.main(ActivityThread.java:6541)
[ExifInterface] 	at java.lang.reflect.Method.invoke(Native Method)
[ExifInterface] 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
[ExifInterface] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by Firice** [comment]
`Unable to save exif Java.IO.IOException: ExifInterface only supports saving attributes on JPEG formats.
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <9ed4c1a7b8844cdcb5330cc881c1cd6a>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <9ed4c1a7b8844cdcb5330cc881c1cd6a>:0 
  at Android.Media.ExifInterface.SaveAttributes () [0x0000a] in <3921e1c40bf740cab0f47696b3ad1282>:0 
  at Plugin.Media.MediaImplementation.PickPhotoAsync (Plugin.Media.Abstractions.PickMediaOptions options) [0x0028e] in <5939e997f291496f805023da28f3a447>:0 
  --- End of managed Java.IO.IOException stack trace ---
java.io.IOException: ExifInterface only supports saving attributes on JPEG formats.
	at android.media.ExifInterface.saveAttributes(ExifInterface.java:1770)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`
