### ISSUE TITLE
[BUG] [ANDROID] Only Oxygen OS 10. Plugin crashes app without possibility to even log the exception (Xamarin Forms and even in Xamarin Android) Info from logcat inside.

### ISSUE THREAD

**Issue by idchlife** [jamesmontemagno/MediaPlugin#834]
## **ONLY Post issues against Latest Beta!!!**

Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 5.0.1 (and previous version beta)
Device Tested On: OnePlus 7 Pro Oxygen OS 10.3.1GM57AA
Simulator Tested On:
Version of VS: VS For Mac 8.6 Preview (8.6 build 3437)
Version of Xamarin: Xamarin Forms 4.5.0.495
Versions of other things you are using: 

### Steps to reproduce the Behavior

1) Develop simple app to take photo/pick photo from gallery.
  a) Follow manual and create all needed permissions and .xml files fot photos/etc
2) Open app on Oxygen OS 10 in OnePlus 7 Pro.
3) See that when taking the photo app just crashes.
4) Try in emulators with Android from 7 to 10. See that everything works fine there.

### Expected Behavior
Photo is being taken or exception is being handled by my try/catch around TakePhotoAsync/PickPhotoAsync
### Actual Behavior
App crashes without any possibility to catch an exception. Only way to discover what's wrong is to connect adb and read logcat.
### Code snippet
Here is code snippet when taking photo:

```csharp
```

Here are essential parts from logcat:

```log
04-07 18:55:46.693 23632 23682 E RequestedPhotoSaveTask: onGenerateFilePath() - Fail to create /my_images/FunnyPhotoApp

04-07 18:55:46.706 23632 23727 E ImageUtils: decodeOrientation() - Fail to access file /my_images/FunnyPhotoApp/check-photo_1.jpg
04-07 18:55:46.706 23632 23727 E ImageUtils: java.io.FileNotFoundException: /my_images/FunnyPhotoApp/check-photo_1.jpg: open failed: ENOENT (No such file or directory)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at libcore.io.IoBridge.open(IoBridge.java:496)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at java.io.FileInputStream.<init>(FileInputStream.java:115)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at com.oneplus.media.ImageUtils.decodeOrientation(ImageUtils.java:1667)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at com.oneplus.camera.io.PhotoSaveTask.onPrepareMediaStoreValues(PhotoSaveTask.java:567)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at com.oneplus.camera.io.MediaSaveTask.insertToMediaStore(MediaSaveTask.java:260)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at com.oneplus.camera.io.PhotoSaveTask.insertToMediaStore(PhotoSaveTask.java:367)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at com.oneplus.camera.io.FileManagerImpl$FileManageerThread$1.handleMessage(FileManagerImpl.java:515)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at android.os.Looper.loop(Looper.java:214)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at android.os.HandlerThread.run(HandlerThread.java:67)
04-07 18:55:46.706 23632 23727 E ImageUtils: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at libcore.io.Linux.open(Native Method)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7581)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	at libcore.io.IoBridge.open(IoBridge.java:482)
04-07 18:55:46.706 23632 23727 E ImageUtils: 	... 10 more
```

**Comment by jamesmontemagno** [comment]
Make sure if you upgrade to the latest package and androidx that you update your file provider: https://github.com/jamesmontemagno/MediaPlugin#android-required-setup

**Comment by GZidar** [comment]
I believe that I have done all those things, but will check again.

**Comment by idchlife** [comment]
@jamesmontemagno for my problem with Oxygen OS (op topic) - everything was up to date. It was the only device that had such problem. Even old Meizu worked flawlessly.

I actually have more information as to mayyyybe where the problem is.
I tried to recreate taking photo functionality from scratch with microsoft tutorial https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/photo-picker#android-implementation
And I discovered that Oxygen OS 10 (others do not do such thing) for some reason always recreates (constructor call, OnCreate call) MainActivity, no matter the options (Launch options SingleInstance, SingleOnTop). Every time photo app opens MainActivity recreates for some reason.
This is just one example of odd behaviour. OnePlus 7 has 8gb of RAM and I suspect the problem not with memory but within some kind of Oxygen OS tweaks that we are kind of unaware of and that these tweaks can disrupt the normal functionality of this plugin.

Unfortunately don't have the device right in front of me, my friend has it and I can only ask him to run something and give me logs :(

If logs do not shed a light on the problem root for you maybe in the future I will be able to spend more time with remote desktop with friends phone and try to discover what is the root of the problem.

@GZidar I'm sorry, but I assume your logs differ and a proper way is to add new issue for your problems.

**Comment by GZidar** [comment]
As an FYI I found what the issue was with my application. As a result of a recent refactor that changed the splash screen in the Android app the MainActivity class had the NoHistory property set to true. This meant that when the camera or the image picker opened the app effectively disappeared from the call stack and the photo or selected image had no way to return causing the screen to disappear as though it had crashed.

So apologies for the misdirection it appears that my problem was my own.

**Comment by lobbo232** [comment]
I think i'm getting a similar issue on a Pixel 4 running Android 10.

When I call PickPhotoAsync or TakePhotoAsync it allows me to take or select the photo but when I confirm it and would expect to be returned to the app it throws a null reference exception instead.
It will never hit the break point I place on my next line of code and it will ignore the try/catch block I have the code inside of.

I have tried the above advice from James with no luck.

**Comment by GZidar** [comment]
If you have upgraded from a previous version then you need to add one more line to the method that calls the plugin to select or take the picture:

await CrossMedia.Current.Initialize();

This was not required in the previous version and I too was getting the null reference exception until I added this line. Check the usage section of the readme in the repo to see exactly where to place this call. I hope that helps.

**Comment by lobbo232** [comment]
@GZidar this is true with the older versions but the latest build removed CrossMedia. After upgrading the CrossMedia namespace was no longer found.

**Comment by GZidar** [comment]
No, check the readme, the requirement is still there, but you no longer need to install CrossMedia as a separate nuget package.

**Comment by lobbo232** [comment]
Sorry, i got confused between your line and `CrossCurrentActivity.Current.Init(this, savedInstanceState);`

Unfortunately adding the initialise line still results in a the null reference line for me.
